export type Json = string | number | boolean | null | Json[] | { [key: string]: Json };

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          role: "admin" | "manager" | "user" | null;
          avatar_url: string | null;
          settings: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          role?: "admin" | "manager" | "user" | null;
          avatar_url?: string | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          role?: "admin" | "manager" | "user" | null;
          avatar_url?: string | null;
          settings?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      vin_records: {
        Row: {
          id: string;
          vin: string;
          manufacturer: string | null;
          brand: string | null;
          model: string | null;
          production_year: number | null;
          market: string | null;
          engine_code: string | null;
          engine_size: string | null;
          fuel_type: string | null;
          transmission: string | null;
          drive_type: "2WD" | "AWD" | "4WD" | "RWD" | "FWD" | null;
          trim_level: string | null;
          body_style: string | null;
          country_of_origin: string | null;
          additional_specs: Json | null;
          decoded_data: Json | null;
          images: string[] | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vin: string;
          manufacturer?: string | null;
          brand?: string | null;
          model?: string | null;
          production_year?: number | null;
          market?: string | null;
          engine_code?: string | null;
          engine_size?: string | null;
          fuel_type?: string | null;
          transmission?: string | null;
          drive_type?: "2WD" | "AWD" | "4WD" | "RWD" | "FWD" | null;
          trim_level?: string | null;
          body_style?: string | null;
          country_of_origin?: string | null;
          additional_specs?: Json | null;
          decoded_data?: Json | null;
          images?: string[] | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vin?: string;
          manufacturer?: string | null;
          brand?: string | null;
          model?: string | null;
          production_year?: number | null;
          market?: string | null;
          engine_code?: string | null;
          engine_size?: string | null;
          fuel_type?: string | null;
          transmission?: string | null;
          drive_type?: "2WD" | "AWD" | "4WD" | "RWD" | "FWD" | null;
          trim_level?: string | null;
          body_style?: string | null;
          country_of_origin?: string | null;
          additional_specs?: Json | null;
          decoded_data?: Json | null;
          images?: string[] | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      parts: {
        Row: {
          id: string;
          vin_id: string | null;
          arabic_name: string | null;
          english_name: string | null;
          part_category: string | null;
          oem_number: string | null;
          alternative_oem_numbers: string[] | null;
          dimensions: Json | null;
          weight: Json | null;
          compatible_vehicles: string[] | null;
          equivalent_parts: Json | null;
          brands: string[] | null;
          notes: string | null;
          attachments: string[] | null;
          quantity: number | null;
          status: "in_stock" | "out_of_stock" | "ordered" | "discontinued" | null;
          images: string[] | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          vin_id?: string | null;
          arabic_name?: string | null;
          english_name?: string | null;
          part_category?: string | null;
          oem_number?: string | null;
          alternative_oem_numbers?: string[] | null;
          dimensions?: Json | null;
          weight?: Json | null;
          compatible_vehicles?: string[] | null;
          equivalent_parts?: Json | null;
          brands?: string[] | null;
          notes?: string | null;
          attachments?: string[] | null;
          quantity?: number | null;
          status?: "in_stock" | "out_of_stock" | "ordered" | "discontinued" | null;
          images?: string[] | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          vin_id?: string | null;
          arabic_name?: string | null;
          english_name?: string | null;
          part_category?: string | null;
          oem_number?: string | null;
          alternative_oem_numbers?: string[] | null;
          dimensions?: Json | null;
          weight?: Json | null;
          compatible_vehicles?: string[] | null;
          equivalent_parts?: Json | null;
          brands?: string[] | null;
          notes?: string | null;
          attachments?: string[] | null;
          quantity?: number | null;
          status?: "in_stock" | "out_of_stock" | "ordered" | "discontinued" | null;
          images?: string[] | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      suppliers: {
        Row: {
          id: string;
          name: string;
          contact_name: string | null;
          email: string | null;
          phone: string | null;
          whatsapp: string | null;
          country: string | null;
          city: string | null;
          address: string | null;
          notes: string | null;
          reliability_score: number | null;
          performance_rating: number | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          contact_name?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          country?: string | null;
          city?: string | null;
          address?: string | null;
          notes?: string | null;
          reliability_score?: number | null;
          performance_rating?: number | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          contact_name?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          country?: string | null;
          city?: string | null;
          address?: string | null;
          notes?: string | null;
          reliability_score?: number | null;
          performance_rating?: number | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          name: string;
          company: string | null;
          email: string | null;
          phone: string | null;
          whatsapp: string | null;
          country: string | null;
          customer_type: "wholesaler" | "dealer" | "retail" | "other" | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          company?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          country?: string | null;
          customer_type?: "wholesaler" | "dealer" | "retail" | "other" | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          company?: string | null;
          email?: string | null;
          phone?: string | null;
          whatsapp?: string | null;
          country?: string | null;
          customer_type?: "wholesaler" | "dealer" | "retail" | "other" | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          vin_id: string | null;
          part_id: string | null;
          customer_id: string | null;
          supplier_id: string | null;
          status: string;
          status_history: Json | null;
          priority: "low" | "normal" | "high" | "urgent" | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number: string;
          vin_id?: string | null;
          part_id?: string | null;
          customer_id?: string | null;
          supplier_id?: string | null;
          status?: string;
          status_history?: Json | null;
          priority?: "low" | "normal" | "high" | "urgent" | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string;
          vin_id?: string | null;
          part_id?: string | null;
          customer_id?: string | null;
          supplier_id?: string | null;
          status?: string;
          status_history?: Json | null;
          priority?: "low" | "normal" | "high" | "urgent" | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          vin_id: string | null;
          part_id: string | null;
          order_id: string | null;
          file_name: string;
          file_path: string;
          file_type: string;
          file_size: number | null;
          mime_type: string | null;
          ocr_text: string | null;
          ocr_confidence: number | null;
          metadata: Json | null;
          uploaded_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          vin_id?: string | null;
          part_id?: string | null;
          order_id?: string | null;
          file_name: string;
          file_path: string;
          file_type: string;
          file_size?: number | null;
          mime_type?: string | null;
          ocr_text?: string | null;
          ocr_confidence?: number | null;
          metadata?: Json | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          vin_id?: string | null;
          part_id?: string | null;
          order_id?: string | null;
          file_name?: string;
          file_path?: string;
          file_type?: string;
          file_size?: number | null;
          mime_type?: string | null;
          ocr_text?: string | null;
          ocr_confidence?: number | null;
          metadata?: Json | null;
          uploaded_by?: string | null;
          created_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          vin_id: string | null;
          part_id: string | null;
          supplier_id: string | null;
          customer_id: string | null;
          channel: string;
          title: string | null;
          participants: string[] | null;
          metadata: Json | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          vin_id?: string | null;
          part_id?: string | null;
          supplier_id?: string | null;
          customer_id?: string | null;
          channel: string;
          title?: string | null;
          participants?: string[] | null;
          metadata?: Json | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          vin_id?: string | null;
          part_id?: string | null;
          supplier_id?: string | null;
          customer_id?: string | null;
          channel?: string;
          title?: string | null;
          participants?: string[] | null;
          metadata?: Json | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          sender: string | null;
          sender_type: string;
          content: string | null;
          content_type: string;
          media_path: string | null;
          timestamp: string | null;
          ocr_extracted_text: string | null;
          ai_summary: string | null;
          ai_entities: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          conversation_id: string;
          sender?: string | null;
          sender_type: string;
          content?: string | null;
          content_type?: string;
          media_path?: string | null;
          timestamp?: string | null;
          ocr_extracted_text?: string | null;
          ai_summary?: string | null;
          ai_entities?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          conversation_id?: string;
          sender?: string | null;
          sender_type?: string;
          content?: string | null;
          content_type?: string;
          media_path?: string | null;
          timestamp?: string | null;
          ocr_extracted_text?: string | null;
          ai_summary?: string | null;
          ai_entities?: Json | null;
          created_at?: string;
        };
      };
      knowledge_entries: {
        Row: {
          id: string;
          title: string | null;
          content: string | null;
          source_type: string;
          source_id: string | null;
          source_table: string | null;
          entities: Json | null;
          embedding: number[] | null;
          confidence: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          title?: string | null;
          content?: string | null;
          source_type: string;
          source_id?: string | null;
          source_table?: string | null;
          entities?: Json | null;
          embedding?: number[] | null;
          confidence?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string | null;
          content?: string | null;
          source_type?: string;
          source_id?: string | null;
          source_table?: string | null;
          entities?: Json | null;
          embedding?: number[] | null;
          confidence?: number | null;
          created_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          reference_type: string | null;
          reference_id: string | null;
          read: boolean | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          reference_type?: string | null;
          reference_id?: string | null;
          read?: boolean | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          reference_type?: string | null;
          reference_id?: string | null;
          read?: boolean | null;
          created_at?: string;
        };
      };
      audit_logs: {
        Row: {
          id: string;
          user_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          changes: Json | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          changes?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          changes?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
    };
  };
};

export type Tables = Database["public"]["Tables"];
export type VinRecord = Tables["vin_records"]["Row"];
export type Part = Tables["parts"]["Row"];
export type Supplier = Tables["suppliers"]["Row"];
export type Customer = Tables["customers"]["Row"];
export type Order = Tables["orders"]["Row"];
export type Document = Tables["documents"]["Row"];
export type Conversation = Tables["conversations"]["Row"];
export type Message = Tables["messages"]["Row"];
export type KnowledgeEntry = Tables["knowledge_entries"]["Row"];
export type Notification = Tables["notifications"]["Row"];
